HelpDesk/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Security.Policy;
using System.Web;

namespace HelpDesk.Models
{
    public class Ticket
    {
        public string Id { get; private set; }
        public string Description { get; private set; }
        public DateTime EntryDate { get; private set; }
        public DateTime? DueDate { get; private set; }
        public bool Solved { get; private set; }

        public Ticket(string description, DateTime? duedate = null)
        {
            Description = description;
            DueDate = duedate;
            EntryDate = DateTime.Now;
            Solved = false;
            Id = Guid.NewGuid().ToString();
        }

        public void MarkSolved()
        {
            this.Solved = true;
        }

    }

}

HelpDesk/ViewModels/TicketViewModel.cs
using HelpDesk.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;

namespace HelpDesk.ViewModels
{
    public class TicketViewModel
    {
        public string Id { get; private set; }
        public string Description { get; private set; }
        public DateTime EntryDate { get; private set; }
        public DateTime? DueDate { get; private set; }
        public bool Solved { get; private set; }
        public string CssClassName { get; private set; }


        public TicketViewModel(Ticket ticket)
        {
            Id = ticket.Id;
            Description = ticket.Description;
            EntryDate = ticket.EntryDate;
            DueDate = ticket.DueDate;
            Solved = ticket.Solved;
            CssClassName = DueDate < DateTime.Now.AddHours(1) ? "danger" : null;
        }
    }

    public class PagedTicketViewModel
    {
        public IPagedList<TicketViewModel> TicketViewModelList { get; set; }
        public int TotalTicketCount { get; set; }
        public int FirstTicketNr { get; set; }
        public int LastTicketNr { get; set; }

        public PagedTicketViewModel(IOrderedEnumerable<Ticket> tickets, int pageSize, int page = 1)
        {
            List<TicketViewModel> ticketVMList = new List<TicketViewModel>();
            foreach (Ticket ticket in tickets)
            {
                var ticketViewModel = new TicketViewModel(ticket);
                ticketVMList.Add(ticketViewModel);
            }
            TicketViewModelList = ticketVMList.ToPagedList(page, pageSize);
            TotalTicketCount = tickets.Count();
            FirstTicketNr = TotalTicketCount > 0 ? page * pageSize - (pageSize - 1) : 0;
            LastTicketNr = TicketViewModelList.Count() > 0 ? FirstTicketNr + (TicketViewModelList.Count() - 1) : FirstTicketNr;
        }
    }

}

HelpDesk/Controllers/TicketController.cs
using HelpDesk.Models;
using HelpDesk.ViewModels;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using HelpDesk.Repositories;

namespace HelpDesk.Controllers
{
    public class TicketController : Controller
    {
        public const int PAGE_SIZE = 10;
        //public static readonly List<Ticket> Tickets = new List<Ticket>();

        private ITicketRepository _ticketRepository;


        public TicketController(ITicketRepository repository)
        {
            this._ticketRepository = repository;
        }

        public ActionResult Index()
        {
            //Display only unsolved tickets on front page
            var ticketViewModels = new List<TicketViewModel>();
            var filteredTickets = _ticketRepository.SelectAll().Where(x => !x.Solved);
            var filteredSortedTickets = filteredTickets.OrderBy(x => !x.DueDate.HasValue)
                .ThenBy(x => x.DueDate);
            foreach (var ticket in filteredSortedTickets) 
            {
                var ticketViewModel = new TicketViewModel(ticket);
                ticketViewModels.Add(ticketViewModel);
            }            
            return View("Index", ticketViewModels);
        }

        public ActionResult All(int page = 1)
        {
            //Use pagination for "All" page
            var orderedTickets = _ticketRepository.SelectAll().OrderBy(x => x.DueDate);
            PagedTicketViewModel pagedTicketViewModel = new PagedTicketViewModel(orderedTickets, PAGE_SIZE, page);
            return View("All", pagedTicketViewModel);
        }

        [HttpPost]
        public ActionResult Add(string description, DateTime? duedate)
        {
            if (description != "")
            {
                var ticketItem = new Ticket(description, duedate);
                _ticketRepository.Insert(ticketItem);
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult MarkSolved(string id)
        {
            _ticketRepository.MarkSolved(id);
                
         
            return RedirectToAction("Index");

        }

        //RANDOM DATA GENERATION

        [HttpPost]
        public ActionResult GenerateData(int count)
        {
            var randomTicketGenerator = new RandomTicketGenerator();
            for (int i = 0; i < count; i++)
            {
                var ticketItem = randomTicketGenerator.CreateTicket();
                _ticketRepository.Insert(ticketItem);
            }
            return RedirectToAction("Index");

        }

    }

}

HelpDesk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HelpDesk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Helpdesk - Ticketing System", "Index", "Ticket", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add A Ticket", "Index", "Ticket")</li>
                    <li>@Html.ActionLink("All Tickets", "All", "Ticket")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HelpDesk Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HelpDesk/Views/Ticket/All.cshtml
@using PagedList;
@using PagedList.Mvc;
@model HelpDesk.ViewModels.PagedTicketViewModel

@{
    ViewBag.Title = "All Tickets";


}

<div id="ticketTableWrapper">
    <h3>@Model.FirstTicketNr - @Model.LastTicketNr / @Model.TotalTicketCount Ticket(s)</h3>
    <table class="table table-hover">
        <tr>
            <th>Description</th>
            <th>Due Date</th>
            <th>Entry Date</th>
            <th>Solved?</th>
        </tr>
        <tbody>

        @foreach (var ticketVM in Model.TicketViewModelList )
        {
            <tr class="@ticketVM.CssClassName">
                <td>
                    @ticketVM.Description
                    </td>
                <td>
                    @ticketVM.DueDate
                </td>
                <td>
                    @ticketVM.EntryDate
                </td>
                <td>
                    @if (ticketVM.Solved){
                        <span class="glyphicon glyphicon-ok text-success"></span>
                    }
                </td>
            </tr>
        
        }
    </table>
    @Html.PagedListPager(Model.TicketViewModelList, page => Url.Action("All", new { page }))
</div>

HelpDesk/Views/Ticket/Index.cshtml
@model List<HelpDesk.ViewModels.TicketViewModel>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
     <h3>Add a ticket</h3>
    <form action="@Url.Action("Add")" method="POST">
        <div class="form-group">
            <label for="desc">Description:</label>
            <textarea class="form-control col-md-12" name="description" id="desc" rows="5" autofocus placeholder="Enter your message.."></textarea>
        </div>
        <div class="form-group">
            <label for="duedate">Deadline:</label>
            <input type="datetime-local" class="form-control" name="duedate" id="duedate" />
        </div>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>

@{
    if (@Model.Count() < 1)
    {

        <form action="@Url.Action("GenerateData")" method="POST">
            <input type="hidden" value="25" name="count" />
            <input type="submit" class="btn btn-success" value="Generate random data">
        </form>
    }

    else
    {
        <div id="ticketTableWrapper">
            <h3>@Model.Count() Active Ticket(s)</h3>
            <table class="table table-hover">
                <tr>
                    <th>Description</th>
                    <th>Due Date</th>
                    <th>Entry Date</th>
                    <th></th>
                </tr>
                <tbody>

                    @foreach (var ticketVM in Model)
                    {
                        <tr class="@ticketVM.CssClassName">
                            <td>
                                @ticketVM.Description
                            </td>
                            <td>
                                @ticketVM.DueDate
                            </td>
                            <td>
                                @ticketVM.EntryDate
                            </td>
                            <td>
                                <form action="@Url.Action("MarkSolved")" method="POST">
                                    <input type="hidden" value="@ticketVM.Id" name="id" />
                                    <input type="submit" class="btn btn-success" value="Mark Solved">
                                </form>
                            </td>
                        </tr>

                    }
            </table>
        </div>
        }
    }